"""MCP tool: metric_sql_preview."""

from __future__ import annotations

from typing import Any, Optional

from mcp_server.mcp_instance import mcp
from mcp_server.semantic_layer import get_client
from mcp_server.tools._common import run_tool


@mcp.tool()
def metric_sql_preview(
    metric_name: str, dimensions: Optional[list[str]] = None
) -> dict[str, Any]:
    """Return the SQL generated by MetricFlow for a metric query (``mf query --explain``).

    The SQL is always produced by MetricFlow itself, never built manually.

    Args:
        metric_name: The metric to preview, e.g. ``total_revenue``.
        dimensions: Optional list of dimensions to group by, e.g. ``["country"]``.

    Returns:
        The standard ``{status, data, error}`` envelope. ``data`` contains
        ``sql``, ``query_plan`` and ``metric_info``.
    """
    return run_tool(get_client().metric_sql_preview, metric_name, dimensions)
